name: Build, Test, Docs, and Deploy

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Install Dependencies
        run: |
          sudo apt-get install -y libudev-dev alsa librust-alsa-sys-dev
          make deps
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Generate Docs
        run: cargo doc --no-deps
      - name: Deploy Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
