name: CI 

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.3
    # - name: Rust Cargo cache
      # uses: raviqqe/cargo-cache@v1
    - name: Install Dependencies
      run: sudo apt-get install -y libudev-dev alsa; make deps
    - name: Build
      run: make build
    - name: Test
      run: make test
          
