name: Build, Test, Docs, and Deploy

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions: write-all

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure cache
        uses: Swatinem/rust-cache@v2.7.3
        with:
          shared-key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Dependencies
        run: |
          sudo apt-get install -y libudev-dev alsa librust-alsa-sys-dev
          make deps
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Generate Docs
        run: cargo doc --no-deps
      - name: Create index.html
        run: echo "<meta http-equiv='refresh' content='0;url=https://sidharthmrao.github.io/TrivialQuest/trivial_quest/index.html'>" > index.html
      - name: Deploy Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
